title: <p align="center">Vinay Prasad </p>
logo: /assets/img/mylogo.jpeg

description:

  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
 
  <br>
  </p>



theme: jekyll-theme-minimal
