title: <p align="center"> Vinay Prasad </p>
logo: /assets/img/mylogo.jpeg

description:

  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  



theme: jekyll-theme-minimal
